[functions]
  included_files = [
    "!node_modules/chrome-aws-lambda/bin/chromium.br",
    "!./node_modules/sharp/vendor/**",
    "!node_modules/sharp/**",
    "!node_modules/sharp/vendor/8.12.2/linux-x64/lib/libvips-cpp.so.42",
  ]