import type { NextPage } from "next";
import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  const [profileImage, setProfileImage] = useState(null as any);
  const [loading, setloading] = useState<boolean>(false);

  const handleSubmitPorfile = async () => {
    setloading(true);
    const res = await fetch("/api/get-profile-picture", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        url: "https://trovo.live/s/BotRix",
      }),
    }).then((res) => res.json());

    setProfileImage(res.image);
    setloading(false);
  };

  return (
    <div className="w-full h-screen bg-[#F5F5F5] flex flex-col">
      <Head>
        <title>TPP Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className=" w-full flex justify-center items-cente fade-in-down-delay-2">
        <div className="text-xl font-extrabold uppercase py-5 text-gray-800">
          <span className="text-[#21B36C]">T</span>PP{" "}
          <span className="text-[#4B9EFF]">Downloader</span>
        </div>
      </nav>

      <main className="flex-1 flex flex-row justify-center items-center">
        <div className="w-[30%] flex flex-col items-center">
          <div className="font-extrabold text-3xl text-gray-800 text-center mb-6 fade-in-down">
            <span className="text-[#21B36C]">Trovo</span> Profile Picture{" "}
            <span className="text-[#4B9EFF]">Downloader</span>
          </div>
          <div className="fade-in-down-delay-1 w-full">
            <label
              htmlFor="search"
              className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300"
            >
              Enter your profile url
            </label>
            <div className="relative">
              <input
                type="search"
                id="search"
                className="block p-4 pl-4 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-[#21B36C] focus:border-[#21B36C] outline-none "
                placeholder="Enter your profile url"
                required
              />
              {loading ? (
                <button className="text-white absolute animate-pulse right-2.5 bottom-2.5 bg-[#21B36C] hover:shadow-lg focus:ring-4 focus:outline-none focus:ring-[#28b47063] font-medium rounded-md text-sm px-4 py-2">
                  Loading...
                </button>
              ) : (
                <button
                  onClick={() => handleSubmitPorfile()}
                  className="text-white absolute right-2.5 bottom-2.5 bg-[#21B36C] hover:shadow-lg focus:ring-4 focus:outline-none focus:ring-[#28b47063] font-medium rounded-md text-sm px-4 py-2"
                >
                  View
                </button>
              )}
            </div>
          </div>
        </div>
        {profileImage && (
          <div
            style={{ width: 500, height: 500, position: "relative" }}
            className="fade-in-left"
          >
            <Image src={profileImage} layout="fill" />
          </div>
        )}
      </main>

      <footer className="w-full h-10">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
